[package]
name = "qliphoth-sys"
version = "0.2.0"
edition = "2025"
description = "Browser API bindings for Qliphoth"
authors = ["Daemoniorum LLC"]
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["rlib"]

[dependencies]
wasm-bindgen = { version = "0.2" }
js-sys = { version = "0.3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3" }
